// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package llminternal

import (
	"context"
	"fmt"
	"sync"

	"google.golang.org/genai"

	"google.golang.org/adk/agent"
	"google.golang.org/adk/model"
	"google.golang.org/adk/session"
)

const (
	// CacheInput identifies audio data received from the user.
	CacheInput = "input"
	// CacheOutput identifies audio data generated by the model.
	CacheOutput = "output"

	// maxCacheBytes is the maximum size (10 MB) before an automatic flush.
	maxCacheBytes = 10 * 1024 * 1024
)

// AudioCacheManager accumulates audio chunks during a live session and
// persists them as artifacts when a turn boundary is reached. It is
// goroutine-safe: the sender loop writes input audio while the receiver
// loop writes output audio concurrently.
type AudioCacheManager struct {
	mu         sync.Mutex
	input      []byte
	output     []byte
	inputMIME  string
	outputMIME string
	turnSeq    int // monotonically increasing turn counter for artifact names
}

// NewAudioCacheManager creates a new cache manager.
func NewAudioCacheManager() *AudioCacheManager {
	return &AudioCacheManager{}
}

// CacheAudio appends audio data to the appropriate buffer. Returns true
// if the buffer exceeded maxCacheBytes and should be flushed.
func (m *AudioCacheManager) CacheAudio(data []byte, mimeType, cacheType string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	switch cacheType {
	case CacheInput:
		m.input = append(m.input, data...)
		if m.inputMIME == "" {
			m.inputMIME = mimeType
		}
		return len(m.input) >= maxCacheBytes
	case CacheOutput:
		m.output = append(m.output, data...)
		if m.outputMIME == "" {
			m.outputMIME = mimeType
		}
		return len(m.output) >= maxCacheBytes
	}
	return false
}

// FlushInput persists the input audio buffer as an artifact and returns
// an event referencing it, or nil if the buffer is empty.
func (m *AudioCacheManager) FlushInput(ctx context.Context, invCtx agent.InvocationContext) *session.Event {
	return m.flush(ctx, invCtx, CacheInput)
}

// FlushOutput persists the output audio buffer as an artifact and returns
// an event referencing it, or nil if the buffer is empty.
func (m *AudioCacheManager) FlushOutput(ctx context.Context, invCtx agent.InvocationContext) *session.Event {
	return m.flush(ctx, invCtx, CacheOutput)
}

func (m *AudioCacheManager) flush(ctx context.Context, invCtx agent.InvocationContext, cacheType string) *session.Event {
	m.mu.Lock()
	var data []byte
	var mimeType string
	switch cacheType {
	case CacheInput:
		data = m.input
		mimeType = m.inputMIME
		m.input = nil
		m.inputMIME = ""
	case CacheOutput:
		data = m.output
		mimeType = m.outputMIME
		m.output = nil
		m.outputMIME = ""
	}
	seq := m.turnSeq
	m.turnSeq++
	m.mu.Unlock()

	if len(data) == 0 {
		return nil
	}
	if mimeType == "" {
		mimeType = "audio/pcm"
	}

	part := &genai.Part{
		InlineData: &genai.Blob{
			MIMEType: mimeType,
			Data:     data,
		},
	}

	var artifacts agent.Artifacts
	if invCtx != nil {
		artifacts = invCtx.Artifacts()
	}
	if artifacts != nil {
		name := fmt.Sprintf("live_audio_%s_%s_%d", invCtx.InvocationID(), cacheType, seq)
		if _, err := artifacts.Save(ctx, name, part); err == nil {
			// Replace inline data with a reference to the artifact.
			part = &genai.Part{
				Text: fmt.Sprintf("[audio artifact: %s]", name),
			}
		}
		// On save failure, fall through and embed inline data directly.
	}

	role := "model"
	author := ""
	invocationID := ""
	branch := ""
	if invCtx != nil {
		invocationID = invCtx.InvocationID()
		branch = invCtx.Branch()
		if invCtx.Agent() != nil {
			author = invCtx.Agent().Name()
		}
	}
	if cacheType == CacheInput {
		role = "user"
		author = "user"
	}

	ev := session.NewEvent(invocationID)
	ev.Author = author
	ev.Branch = branch
	ev.LLMResponse = model.LLMResponse{
		Content: &genai.Content{
			Role:  role,
			Parts: []*genai.Part{part},
		},
	}
	return ev
}
